AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: testLambdaExecutionRole
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
        Path: /
        Policies:
        - PolicyName: root
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
              - "logs:*"
              - "xray:*"
              Resource: "*"
Outputs:
  LambdaExecutionRole:
    Value: !Ref 'LambdaExecutionRole'
    Export:
      Name: testLambdaExecutionRole