---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pigumergroup/ubuntu-sbt

params:
  ACCESS_KEY_ID:
  SECRET_ACCESS_KEY:

inputs:
  - name: source

run:
  dir: source
  path: ci/build.sh
