---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dockanteam/alpine-sbt

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

inputs:
  - name: sbt-aws-cloudformation-src

run:
  dir: sbt-aws-cloudformation-src
  path: ci/build.sh
